// <auto-generated />
using BankingApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApi.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    [Migration("20260826120810_AdicionarTabelaClientes")]
    partial class AdicionarTabelaClientes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("BankingApi.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BankingApi.Models.ContaBancaria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("BankingApi.Models.ContaBancaria", b =>
                {
                    b.OwnsOne("BankingApi.Models.Endereco", "EnderecoCobranca", b1 =>
                        {
                            b1.Property<int>("ContaBancariaID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ContaBancariaID");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaBancariaID");
                        });

                    b.Navigation("EnderecoCobranca");
                });
#pragma warning restore 612, 618
        }
    }
}
