// <auto-generated />
using System;
using BankingApi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankingApi.Infrastructure.Migrations
{
    [DbContext(typeof(BancoDbContext))]
    [Migration("20260826142206_AtualizandoEnderecoCobranca")]
    partial class AtualizandoEnderecoCobranca
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.30");

            modelBuilder.Entity("BankingApi.Domain.Models.CartaoCredito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiaVencimento")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LimiteDisponivel")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LimiteTotal")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroCartao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.ContaBancaria", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ClienteId");

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.Transacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContaBancariaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContaBancariaId");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.CartaoCredito", b =>
                {
                    b.HasOne("BankingApi.Domain.Models.Cliente", "Cliente")
                        .WithMany("Cartoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.ContaBancaria", b =>
                {
                    b.HasOne("BankingApi.Domain.Models.Cliente", "Cliente")
                        .WithMany("Contas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("BankingApi.Domain.Models.Endereco", "EnderecoCobranca", b1 =>
                        {
                            b1.Property<int>("ContaBancariaID")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Cidade")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoCobranca_Cidade");

                            b1.Property<string>("Estado")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoCobranca_Estado");

                            b1.Property<string>("Rua")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoCobranca_Rua");

                            b1.HasKey("ContaBancariaID");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaBancariaID");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("EnderecoCobranca")
                        .IsRequired();
                });

            modelBuilder.Entity("BankingApi.Domain.Models.Transacao", b =>
                {
                    b.HasOne("BankingApi.Domain.Models.ContaBancaria", "ContaBancaria")
                        .WithMany("Transacoes")
                        .HasForeignKey("ContaBancariaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaBancaria");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.Cliente", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Contas");
                });

            modelBuilder.Entity("BankingApi.Domain.Models.ContaBancaria", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
